name:                midterm-review-session
version:             0.1.0.0

extra-source-files:
- README.md

description:         midterm-review-session

ghc-options:
- -Wall
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wno-unused-top-binds
- -Wno-unused-local-binds
- -Wno-unused-pattern-binds
- -Wno-unused-matches
- -Wno-missing-signatures
- -Wno-type-defaults
- -Wno-compat-unqualified-imports
- -Wno-name-shadowing
- -fdefer-typed-holes

language: GHC2024

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src

executables:
  midterm-review-session-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - midterm-review-session
    when:
    - condition: false
      other-modules: Paths_midterm_review_session

tests:
  midterm-review-session-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - midterm-review-session
    - hspec
    - hspec-discover
    - QuickCheck
